name: ramp-stroke
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib
  # Extra requirements
  - tensorflow-gpu<2.4
  - pytorch
  - keras
  - lightgbm
  - nilearn
  - scikit-image>=0.18
  - pip
  - pip:
    - git+https://github.com/paris-saclay-cds/ramp-workflow
    - git+https://github.com/AlexandreHutton/stroke
    - wget
    - ramp-utils
    - imbalanced-learn
    - tensorflow-addons<0.12
    - bids
    # Extra requirements pip
    - xgboost
    - catboost
    - jupyterlab
