name: ramp-stroke
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - numpy==1.23.4
  - scikit-learn>=0.22
  - scipy
  - click
  - pandas
  - matplotlib-base

  # Extra requirements
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - lightgbm
  - nilearn
  - scikit-image>=0.18
  - transformers
  - datasets

  - pip
  - pip:
    - wheel
    - ramp-workflow
    - git+https://github.com/ramp-kits/stroke_lesions
    - wget
    - ramp-utils
    - imbalanced-learn
    - bids
    - osfclient
    # Extra requirements pip
    - xgboost
    - catboost
    - jupyterlab
    - jupyter_contrib_nbextensions
